spring:
  datasource:
    driverClassName: org.h2.Driver
    password: password
    url: jdbc:h2:file:./backend/db/test
    username: sa
  h2:
    console:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update # turn off for production
    show-sql: true